services:
  - type: web
    name: repo4-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn news_aggregator.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"